welcome:  |
  ════════════════════════════════════
  ▄▄      ▄▄    ▄▄        ▄▄        ▄▄ 
   █████░  ██████░ ██████░ ████░ ████░ 
    ██████░ ████░ ████████░████░ ████░ 
    ██░ ███░ ██░  ███░   █▌ ██░   ██░ 
    ██░  ██░ ██░  ███░    ▌ ██░   ██░ 
    ██░  ██░ ██░   █████░   ████████░ 
    ██░  ██░ ██░    █████░  ████████░ 
    ██░  ██░ ██░ ▐░    ███░ ██░   ██░ 
    ██░ ██░  ██░ ▐█░   ███░ ██░   ██░ 
    ██████░ ████░ ████████░████░ ████░ 
   █████░  ██████░ ██████░ ████░ ████░ 
  ▀▀      ▀▀    ▀▀        ▀▀        ▀▀ 
  ════════════════════════════════════
  d  i  s  h    s  h  e  l  l    0 . 0

  [ • ] Type 'help' for the list of built-in commands

prompt: "┌─(dish•___)-[~]\n└$ " # stolen from kali linux
